### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by emanruse** [kennethrrosen/qubes-really-disp-vm#1]
Instead of deleting the log files post-factum, wouldn't it be wiser to make them links to `/dev/null` before starting the VM, then simply removing the links? Then there will be no saving of logs, hence less file system evidence the VM has ever existed.

Reported upstream too:

https://github.com/unman/notes/issues/9

**Comment by kennethrrosen** [comment]
@emanruse happy to consider; please send your script-change suggestions

**Comment by emanruse** [comment]
https://forum.qubes-os.org/t/really-disposable-ram-based-qubes/21532
